name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEBIAN_FRONTEND: noninteractive  # 避免安装过程中的交互提示

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up swap space (4GB)
      run: |
        sudo fallocate -l 4G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        free -h

    - name: Configure system
      run: |
        # 启用所有Ubuntu仓库并更新
        sudo add-apt-repository -y universe
        sudo add-apt-repository -y multiverse
        sudo apt-get update -qq

    - name: Install system dependencies
      run: |
        # 基础构建工具
        sudo apt-get install -y --no-install-recommends \
          software-properties-common \
          build-essential \
          git zip unzip \
          openjdk-17-jdk \
          python3-pip python3-dev \
          autoconf libtool pkg-config \
          zlib1g-dev libncurses-dev \
          cmake libffi-dev libssl-dev

        # 处理libtinfo兼容性问题
        sudo apt-get install -y libtinfo6 || \
        (echo "Installing libtinfo5 alternative..." && \
         wget http://archive.ubuntu.com/ubuntu/pool/main/n/ncurses/libtinfo5_6.2-0ubuntu2_amd64.deb && \
         sudo dpkg -i libtinfo5_6.2-0ubuntu2_amd64.deb || true)

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install --no-cache-dir \
          buildozer \
          cython==0.29.33 \
          virtualenv

    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug
        ls -lh bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
        retention-days: 5
