name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up swap space (4GB)
      run: |
        sudo fallocate -l 4G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        free -h

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository universe
        sudo apt-get update -qq
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          python3-pip autoconf libtool \
          pkg-config zlib1g-dev libncurses5-dev \
          libncursesw5-dev libtinfo5 cmake \
          libffi-dev libssl-dev

    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install --no-cache-dir \
          buildozer \
          cython==0.29.33 \
          virtualenv

    - name: Build APK (Debug)
      run: |
        echo "=== Starting build ==="
        buildozer android clean
        buildozer -v android debug
        echo "=== Build complete ==="
        
        # Check generated APK
        ls -lh bin/
        file bin/*.apk

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
        retention-days: 5
