name: Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          python3-pip autoconf libtool \
          pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev \
          libtinfo5 cmake

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.33 virtualenv

    - name: Build APK
      run: |
        buildozer -v android debug
        cp bin/*.apk .

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-apk
        path: '*.apk'
