name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEBIAN_FRONTEND: noninteractive
  BUILDODER_DIR: /home/runner/work/${{ github.repository }}/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up swap space (6GB)
      run: |
        sudo fallocate -l 6G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        free -h

    - name: Configure system
      run: |
        sudo add-apt-repository -y universe
        sudo add-apt-repository -y multiverse
        sudo apt-get update -qq

    - name: Install system dependencies
      run: |
        sudo apt-get install -y --no-install-recommends \
          software-properties-common \
          build-essential \
          git zip unzip \
          openjdk-17-jdk \
          python3-pip python3-dev \
          autoconf libtool pkg-config \
          zlib1g-dev libncurses-dev \
          cmake libffi-dev libssl-dev \
          libtinfo6

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip wheel
        pip install --no-cache-dir \
          buildozer==1.5.0 \
          cython==0.29.33

    - name: Prepare build environment
      run: |
        mkdir -p $BUILDODER_DIR/.buildozer/android/platform
        echo "buildozer_dir = $BUILDODER_DIR/.buildozer" >> buildozer.spec

    - name: Build APK (with retry)
      run: |
        buildozer android clean || true
        for i in {1..3}; do
          buildozer -v android debug && break
          echo "Build attempt $i failed, retrying..."
          sleep 10
        done

    - name: Verify APK
      run: |
        file bin/*.apk
        ls -lh bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: comic-reader-apk
        path: bin/*.apk
        retention-days: 7
